import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check, User, Bot, RotateCcw, Play, X, Github, Loader2 } from "lucide-react";
import type { ChatMessage } from "@/types/chat";
import { useAuth } from "@/_core/hooks/useAuth";
import { SmolGameAPI } from "@/lib/smolgame-api";

interface ChatMessageItemProps {
  message: ChatMessage;
  onRetry?: () => void;
}

export function ChatMessageItem({ message, onRetry }: ChatMessageItemProps) {
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [isDeploying, setIsDeploying] = useState(false);
  const [deployStatus, setDeployStatus] = useState("");
  const [deployResult, setDeployResult] = useState<{ gameUrl: string; repoUrl: string } | null>(null);
  const isUser = message.role === "user";
  const isStreaming = message.isStreaming;
  const { isAuthenticated, login } = useAuth();

  const htmlCode = message.content.match(/<game_prototype>\s*([\s\S]*?)(?:<\/game_prototype>|$)/)?.[1] ||
                   message.content.match(/```html\s*([\s\S]*?)```/)?.[1] || 
                   (message.content.includes('<html>') ? message.content : null);

  const handleCopy = async () => {
    try {
      const cleanContent = message.content.replace(/<game_prototype>[\s\S]*?(?:<\/game_prototype>|$)/g, '').trim();
      await navigator.clipboard.writeText(htmlCode || cleanContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleDeploy = async () => {
    if (!isAuthenticated) {
      if (confirm("Пожалуйста, подключи GitHub для публикации игры. Подключить сейчас?")) {
        login();
      }
      return;
    }

    if (!htmlCode) return;

    setIsDeploying(true);
    setDeployStatus("Подготовка файлов...");

    try {
      const gameTitle = message.content.slice(0, 30).split('\n')[0] || "Smol Game Prototype";
      setDeployStatus("Отправка в репозиторий...");
      
      const result = await SmolGameAPI.publishGame({
        gameTitle,
        files: [{ path: "index.html", content: htmlCode }],
        gameDescription: "Generated by OpenSmolGame AI Architect"
      });

      if (result.ok) {
        setDeployResult({
          gameUrl: result.pagesUrl,
          repoUrl: `https://github.com/${result.repo}`
        });
        setDeployStatus("Готово!");
      } else {
        throw new Error(result.error || "Deployment failed");
      }
    } catch (err) {
      console.error("Deploy error:", err);
      setDeployStatus(`Ошибка: ${err instanceof Error ? err.message : "Неизвестная ошибка"}`);
      setTimeout(() => setDeployStatus(""), 5000);
    } finally {
      setIsDeploying(false);
    }
  };

  return (
    <div className={`flex gap-4 py-8 px-4 ${isUser ? "bg-transparent" : "bg-[#13141a]/30"}`}>
      <div className="flex-shrink-0">
        <div className={`w-9 h-9 rounded-xl flex items-center justify-center ${isUser ? "bg-[#1c1e26] text-white/50" : "bg-[#a3b8d4]/10 text-[#a3b8d4]"}`}>
          {isUser ? <User size={18} /> : <Bot size={18} />}
        </div>
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs font-black uppercase tracking-widest text-white/30">
            {isUser ? "Пользователь" : "Smol Agent"}
          </span>
          <span className="text-[10px] text-white/10">
            {new Date(message.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
          </span>
        </div>
        <div className="prose prose-invert max-w-none">
          {isUser ? (
            <p className="text-white/80 leading-relaxed whitespace-pre-wrap text-sm font-medium">
              {message.content}
            </p>
          ) : (
            <div className="markdown-content text-white/90">
              {message.content ? (
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {message.role === 'assistant' 
                    ? message.content.replace(/<game_prototype>[\s\S]*?(?:<\/game_prototype>|$)/g, '').trim() 
                    : message.content}
                </ReactMarkdown>
              ) : isStreaming ? (
                <div className="flex items-center gap-1.5 text-[#a3b8d4]">
                  <div className="w-1.5 h-1.5 rounded-full bg-[#a3b8d4] animate-bounce [animation-delay:0ms]" />
                  <div className="w-1.5 h-1.5 rounded-full bg-[#a3b8d4] animate-bounce [animation-delay:150ms]" />
                  <div className="w-1.5 h-1.5 rounded-full bg-[#a3b8d4] animate-bounce [animation-delay:300ms]" />
                </div>
              ) : null}
            </div>
          )}
        </div>

        {!isUser && message.content && !isStreaming && (
          <div className="flex flex-col gap-4 mt-6">
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="sm"
                className="h-8 px-3 text-[10px] font-bold uppercase tracking-widest text-[#a3b8d4] hover:text-white bg-[#13141a] border border-white/5 rounded-xl transition-all"
                onClick={handleCopy}
              >
                {copied ? <Check size={14} /> : <Copy size={14} />}
                <span className="ml-2">{copied ? "Скопировано" : "Копировать"}</span>
              </Button>
              {onRetry && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-8 px-3 text-[10px] font-bold uppercase tracking-widest text-white/30 hover:text-white bg-[#13141a] border border-white/5 rounded-xl transition-all"
                  onClick={onRetry}
                >
                  <RotateCcw size={14} />
                  <span className="ml-2">Переделать</span>
                </Button>
              )}
            </div>

            {message.status && (
              <div className="flex items-center gap-2 text-[10px] text-[#a3b8d4] font-black uppercase tracking-tighter bg-[#a3b8d4]/5 p-3 rounded-xl border border-[#a3b8d4]/10 w-fit">
                <div className="w-1.5 h-1.5 rounded-full bg-[#a3b8d4] animate-pulse" />
                <span>{message.status}</span>
              </div>
            )}

            {message.pipelineResult && (
              <div className="p-4 bg-[#13141a] border border-white/5 rounded-2xl animate-in fade-in zoom-in duration-300">
                <div className="flex items-center justify-between mb-3">
                  <h5 className="text-[10px] font-black uppercase tracking-widest text-white/20">Анализ качества</h5>
                  <span className={`text-xs font-black ${message.pipelineResult.finalScore >= 70 ? 'text-green-500' : 'text-yellow-500'}`}>
                    {message.pipelineResult.finalScore}/100
                  </span>
                </div>
                
                {message.pipelineResult.isPublishable ? (
                  <div className="space-y-4">
                    <p className="text-[10px] text-green-500 font-black uppercase tracking-wider flex items-center gap-2">
                      <Check size={14} strokeWidth={3} /> Готово к публикации
                    </p>
                    
                    {!deployResult ? (
                      <Button
                        variant="default"
                        size="sm"
                        disabled={isDeploying}
                        className="w-full h-10 text-[11px] font-black uppercase tracking-widest gap-2 bg-[#a3b8d4] text-[#0a0b0e] hover:bg-[#a3b8d4]/90 rounded-xl"
                        onClick={handleDeploy}
                      >
                        {isDeploying ? (
                          <>
                            <Loader2 size={14} className="animate-spin" />
                            {deployStatus || "Публикация..."}
                          </>
                        ) : (
                          <>
                            <Github size={14} />
                            Публикация в SmolGame
                          </>
                        )}
                      </Button>
                    ) : (
                      <div className="space-y-2">
                        <Button
                          className="w-full h-10 bg-green-500 text-white font-black uppercase tracking-widest text-[11px] rounded-xl"
                          onClick={() => window.open(deployResult.gameUrl, '_blank')}
                        >
                          <Play size={14} fill="currentColor" className="mr-2" /> Открыть игру
                        </Button>
                        <Button
                          variant="ghost"
                          className="w-full h-8 text-[9px] text-white/30 hover:text-white"
                          onClick={() => window.open(deployResult.repoUrl, '_blank')}
                        >
                          <Github size={12} className="mr-2" /> Посмотреть код в GitHub
                        </Button>
                      </div>
                    )}
                  </div>
                ) : (
                  <div className="space-y-2">
                    <p className="text-[10px] text-yellow-500/50 font-bold uppercase tracking-wider">Требуются доработки:</p>
                    {message.pipelineResult.nextSteps.slice(0, 3).map((step: string, i: number) => (
                      <p key={i} className="text-[10px] text-white/40 flex gap-2">
                        <span className="text-[#a3b8d4]">•</span> {step}
                      </p>
                    ))}
                  </div>
                )}
              </div>
            )}

            {htmlCode && !message.pipelineResult && (
              <div className="p-5 bg-[#a3b8d4]/5 border border-[#a3b8d4]/20 rounded-2xl">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <h4 className="text-xs font-black text-[#a3b8d4] uppercase tracking-widest">Прототип готов</h4>
                    <p className="text-[10px] text-white/30 mt-1">Проверь механику перед деплоем</p>
                  </div>
                  <Button
                    variant="default"
                    className="h-10 px-6 bg-[#a3b8d4] text-[#0a0b0e] font-black uppercase tracking-widest text-[10px] rounded-xl hover:scale-105 transition-transform"
                    onClick={() => setShowPreview(true)}
                  >
                    <Play size={14} fill="currentColor" className="mr-2" /> Запустить
                  </Button>
                </div>
              </div>
            )}
          </div>
        )}

        {showPreview && htmlCode && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/90 backdrop-blur-xl">
            <div className="relative w-full max-w-lg aspect-[9/16] bg-black rounded-[32px] overflow-hidden shadow-2xl border border-white/10 ring-1 ring-white/20">
              <div className="absolute top-6 right-6 z-50">
                <Button 
                  variant="ghost" 
                  size="sm" 
                  className="rounded-full w-10 h-10 p-0 bg-black/50 text-white hover:bg-black border border-white/10"
                  onClick={() => setShowPreview(false)}
                >
                  <X size={20} />
                </Button>
              </div>
              <iframe
                title="Game Preview"
                srcDoc={htmlCode.includes('<!DOCTYPE') ? htmlCode : `<!DOCTYPE html><html><body style="margin:0;overflow:hidden;background:#000;">${htmlCode}</body></html>`}
                className="w-full h-full border-none"
                sandbox="allow-scripts allow-modals"
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
