import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check, User, Bot, RotateCcw, Play, X, Github, Rocket, Loader2, Globe } from "lucide-react";
import type { ChatMessage } from "@/types/chat";
import { useAuth } from "@/_core/hooks/useAuth";
import { SmolGameAPI } from "@/lib/smolgame-api";


interface ChatMessageItemProps {
  message: ChatMessage;
  onRetry?: () => void;
}

export function ChatMessageItem({ message, onRetry }: ChatMessageItemProps) {
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [isDeploying, setIsDeploying] = useState(false);
  const [deployStatus, setDeployStatus] = useState("");
  const [deployResult, setDeployResult] = useState<{ gameUrl: string; repoUrl: string } | null>(null);
  const isUser = message.role === "user";
  const isStreaming = message.isStreaming;
  const { isAuthenticated, login } = useAuth();

  const htmlCode = message.content.match(/```html\s*([\s\S]*?)```/)?.[1] || 
                   (message.content.includes('<html>') ? message.content : null);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(message.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleDeploy = async () => {
    if (!isAuthenticated) {
      if (confirm("Пожалуйста, подключи GitHub для публикации игры. Подключить сейчас?")) {
        login();
      }
      return;
    }

    if (!htmlCode) return;

    setIsDeploying(true);
    setDeployStatus("Подготовка файлов...");

    try {
      const gameTitle = message.content.slice(0, 30).split('\n')[0] || "Smol Game Prototype";
      
      setDeployStatus("Отправка в репозиторий...");
      
      const result = await SmolGameAPI.publishGame({
        gameTitle,
        files: [
          { path: "index.html", content: htmlCode }
        ],
        gameDescription: "Generated by OpenSmolGame AI Architect"
      });

      if (result.ok) {
        setDeployResult({
          gameUrl: result.pagesUrl,
          repoUrl: `https://github.com/${result.repo}`
        });
        setDeployStatus("Готово!");
      } else {
        throw new Error(result.error || "Deployment failed");
      }
    } catch (err) {
      console.error("Deploy error:", err);
      setDeployStatus(`Ошибка: ${err instanceof Error ? err.message : "Неизвестная ошибка"}`);
      setTimeout(() => setDeployStatus(""), 5000);
    } finally {
      setIsDeploying(false);
    }
  };

  return (
    <div className={`flex gap-4 py-6 px-4 ${isUser ? "bg-transparent" : "bg-card/50"}`}>
      <div className="flex-shrink-0">
        <div
          className={`w-8 h-8 rounded-lg flex items-center justify-center ${
            isUser
              ? "bg-secondary text-foreground"
              : "bg-primary/20 text-primary"
          }`}
        >
          {isUser ? <User size={16} /> : <Bot size={16} />}
        </div>
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-1.5">
          <span className="text-sm font-medium text-foreground">
            {isUser ? "You" : "Smol-agent"}
          </span>
          <span className="text-xs text-muted-foreground">
            {new Date(message.timestamp).toLocaleTimeString([], {
              hour: "2-digit",
              minute: "2-digit",
            })}
          </span>
        </div>
        <div className="prose prose-invert max-w-none">
          {isUser ? (
            <p className="text-foreground leading-relaxed whitespace-pre-wrap">
              {message.content}
            </p>
          ) : (
            <div className="markdown-content text-foreground/90">
              {message.content ? (
                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                  {message.content}
                </ReactMarkdown>
              ) : isStreaming ? (
                <div className="flex items-center gap-1.5 text-muted-foreground">
                  <div className="w-1.5 h-1.5 rounded-full bg-primary animate-bounce [animation-delay:0ms]" />
                  <div className="w-1.5 h-1.5 rounded-full bg-primary animate-bounce [animation-delay:150ms]" />
                  <div className="w-1.5 h-1.5 rounded-full bg-primary animate-bounce [animation-delay:300ms]" />
                  <span className="text-sm ml-1">Thinking...</span>
                </div>
              ) : null}
            </div>
          )}
        </div>
        {!isUser && message.content && !isStreaming && (
          <div className="flex items-center gap-1 mt-3 opacity-0 group-hover:opacity-100 transition-opacity">
            <Button
              variant="ghost"
              size="sm"
              className="h-7 px-2 text-xs text-muted-foreground hover:text-foreground"
              onClick={handleCopy}
            >
              {copied ? <Check size={12} /> : <Copy size={12} />}
              <span className="ml-1">{copied ? "Copied" : "Copy"}</span>
            </Button>
            {onRetry && (
              <Button
                variant="ghost"
                size="sm"
                className="h-7 px-2 text-xs text-muted-foreground hover:text-foreground"
                onClick={onRetry}
              >
                <RotateCcw size={12} />
                <span className="ml-1">Retry</span>
              </Button>
            )}
            {message.status && (
              <div className="flex items-center gap-2 mt-3 mb-2 text-[10px] text-primary/70 animate-pulse font-mono">
                <div className="w-1.5 h-1.5 rounded-full bg-primary animate-bounce" />
                <span>{message.status}</span>
              </div>
            )}

            {message.pipelineResult && (
              <div className="mt-3 p-3 bg-sidebar-accent/30 border border-sidebar-border rounded-xl animate-in fade-in zoom-in duration-300">
                <div className="flex items-center justify-between mb-2">
                  <h5 className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Production Quality Report</h5>
                  <div className="flex items-center gap-2">
                    <span className={`text-xs font-black ${message.pipelineResult.finalScore >= 70 ? 'text-green-500' : 'text-yellow-500'}`}>
                      {message.pipelineResult.finalScore}/100
                    </span>
                  </div>
                </div>
                
                {!message.pipelineResult.isPublishable && message.pipelineResult.nextSteps.length > 0 && (
                  <div className="space-y-1 mt-2 border-t border-sidebar-border pt-2">
                    {message.pipelineResult.nextSteps.slice(0, 3).map((step: string, i: number) => (
                      <p key={i} className="text-[9px] text-foreground/60 flex gap-2 leading-tight">
                        <span className="text-primary font-bold">!</span> {step}
                      </p>
                    ))}
                  </div>
                )}
                
                {message.pipelineResult.isPublishable && (
                  <>
                    <p className="text-[10px] text-green-500 font-bold flex items-center gap-1 mt-1">
                      <Check size={10} /> Проверено. Готово к публикации.
                    </p>
                    
                    {!deployResult && (
                      <div className="mt-3 flex gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          disabled={isDeploying}
                          className="w-full h-8 text-[10px] font-bold gap-2 border-primary/20 hover:bg-primary/5"
                          onClick={handleDeploy}
                        >
                          {isDeploying ? (
                            <>
                              <Loader2 size={12} className="animate-spin" />
                              {deployStatus || "Publishing..."}
                            </>
                          ) : (
                            <>
                              <Github size={12} />
                              {!!(window as any).Telegram?.WebApp?.initData ? "Publish to SmolGame" : "Publish to GitHub Pages"}
                            </>
                          )}
                        </Button>
                      </div>
                    )}

                    {deployResult && (
                      <div className="mt-3 p-2 bg-green-500/10 border border-green-500/20 rounded-lg animate-in zoom-in duration-300">
                        <p className="text-[10px] text-green-500 font-bold mb-2 flex items-center gap-1">
                          <Rocket size={12} /> Live on GitHub!
                        </p>
                        <div className="flex gap-2">
                          <Button
                            variant="link"
                            size="sm"
                            className="h-6 p-0 text-[9px] text-primary"
                            onClick={() => window.open(deployResult.gameUrl, '_blank')}
                          >
                            <Globe size={10} className="mr-1" /> View Game
                          </Button>
                          <Button
                            variant="link"
                            size="sm"
                            className="h-6 p-0 text-[9px] text-muted-foreground"
                            onClick={() => window.open(deployResult.repoUrl, '_blank')}
                          >
                            <Github size={10} className="mr-1" /> View Repo
                          </Button>
                        </div>
                      </div>
                    )}
                  </>
                )}
              </div>
            )}

            {htmlCode && (
              <div className="mt-4 p-4 border-2 border-primary/30 rounded-2xl bg-primary/5 animate-in fade-in slide-in-from-bottom-2 duration-500">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <h4 className="text-sm font-black text-primary uppercase tracking-tighter italic">Prototype Ready!</h4>
                    <p className="text-[10px] text-muted-foreground">Click to test mechanics in real-time</p>
                  </div>
                  <Button
                    variant="default"
                    size="lg"
                    className="h-12 px-8 bg-primary text-primary-foreground hover:bg-primary/90 border-none shadow-[0_0_20px_rgba(var(--primary),0.3)] animate-pulse hover:animate-none group"
                    onClick={() => setShowPreview(true)}
                  >
                    <Play size={18} fill="currentColor" className="mr-2 group-hover:scale-110 transition-transform" />
                    <span className="font-black italic text-lg">PLAY NOW</span>
                  </Button>
                </div>
              </div>
            )}
          </div>
        )}

        {showPreview && htmlCode && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/80 backdrop-blur-md">
            <div className="relative w-full max-w-5xl aspect-video bg-white rounded-2xl overflow-hidden shadow-2xl border border-white/10">
              <div className="absolute top-4 right-4 z-50">
                <Button 
                  variant="destructive" 
                  size="sm" 
                  className="rounded-full w-8 h-8 p-0"
                  onClick={() => setShowPreview(false)}
                >
                  <X size={16} />
                </Button>
              </div>
              <iframe
                title="Game Preview"
                srcDoc={htmlCode.includes('<!DOCTYPE') ? htmlCode : `<!DOCTYPE html><html><body style="margin:0;overflow:hidden;background:#000;">${htmlCode}</body></html>`}
                className="w-full h-full border-none bg-black"
                sandbox="allow-scripts allow-modals"
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
