import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Check, User, Bot, RotateCcw, Play, X, Github, Loader2, Clock, ExternalLink } from "lucide-react";
import type { ChatMessage } from "@/types/chat";
import { useAuth } from "@/_core/hooks/useAuth";
import { SmolGameAPI } from "@/lib/smolgame-api";

interface ChatMessageItemProps {
  message: ChatMessage;
  onRetry?: () => void;
  onSend?: (content: string) => void;
  onSwitchTab?: (tab: "chat" | "studio") => void;
  isLast?: boolean;
}

const extractTextFromNode = (node: any): string => {
  if (!node) return "";
  if (node.type === "text") return node.value || "";
  if (node.children) return node.children.map(extractTextFromNode).join("");
  return "";
};

type DeployState =
  | { phase: "idle" }
  | { phase: "deploying"; status: string }
  | { phase: "waiting_pages"; pagesUrl: string; repoUrl: string; attempt: number; maxAttempts: number }
  | { phase: "ready"; pagesUrl: string; repoUrl: string }
  | { phase: "error"; message: string };

export function ChatMessageItem({ message, onRetry, onSend, onSwitchTab, isLast }: ChatMessageItemProps) {
  const [copied, setCopied] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [deployState, setDeployState] = useState<DeployState>({ phase: "idle" });
  const { isAuthenticated, isGithubConnected, login, refresh: refreshAuth } = useAuth();

  const htmlCode =
    message.content.match(/<game_prototype>\s*([\s\S]*?)(?:<\/game_prototype>|$)/)?.[1] ||
    message.content.match(/```html\s*([\s\S]*?)```/)?.[1] ||
    message.content.match(/(<html[\s\S]*<\/html>)/i)?.[1] ||
    null;

  // ── Синхронизация auth-пользователя в глобал для useChat авто-деплоя ──
  useEffect(() => {
    (window as any).__smolAuthUser = { isGithubConnected };
  }, [isGithubConnected]);

  // ── Подхватить pending-игру после OAuth-редиректа ─────────────────────
  useEffect(() => {
    if (!isGithubConnected) return;
    const pending = SmolGameAPI.popPendingGame();
    if (!pending) return;
    // Запускаем деплой автоматически
    runDeploy(pending.htmlCode, pending.title);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isGithubConnected]);

  // ── Polling GitHub Pages в фоне ───────────────────────────────────────
  useEffect(() => {
    if (deployState.phase !== "waiting_pages") return;
    const { pagesUrl, repoUrl } = deployState;

    let cancelled = false;
    SmolGameAPI.pollPagesReady(pagesUrl, (attempt, max) => {
      if (!cancelled) {
        setDeployState({ phase: "waiting_pages", pagesUrl, repoUrl, attempt, maxAttempts: max });
      }
    }).then((ready) => {
      if (!cancelled) {
        setDeployState({ phase: "ready", pagesUrl, repoUrl });
        if (!ready) {
          // Время вышло, но ссылку всё равно показываем
          console.warn("[Pages polling] timeout — showing link anyway");
        }
      }
    });

    return () => { cancelled = true; };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [deployState.phase === "waiting_pages" ? deployState.pagesUrl : null]);

  // ── Синхронизация deployResult из useChat (авто-деплой) ──────────────
  useEffect(() => {
    const dr = (message as any).deployResult;
    if (!dr || deployState.phase !== "idle") return;
    if (dr.pagesReady) {
      setDeployState({ phase: "ready", pagesUrl: dr.pagesUrl, repoUrl: dr.repoUrl });
    } else {
      setDeployState({ phase: "waiting_pages", pagesUrl: dr.pagesUrl, repoUrl: dr.repoUrl, attempt: 1, maxAttempts: 24 });
    }
  }, [(message as any).deployResult]);

  // ── Центральная функция деплоя ─────────────────────────────────────────
  const runDeploy = async (code: string, title: string) => {
    setDeployState({ phase: "deploying", status: "Подготовка файлов..." });
    try {
      setDeployState({ phase: "deploying", status: "Отправка в репозиторий..." });
      const result = await SmolGameAPI.publishGame({
        gameTitle: title,
        files: [{ path: "index.html", content: code }],
        gameDescription: "Generated by SmolGame AI Architect",
      });

      if (!result.ok) throw new Error(result.error || "Deployment failed");

      const pagesUrl: string = result.pagesUrl;
      const repoUrl = `https://github.com/${result.repo}`;

      if (result.pagesReady) {
        setDeployState({ phase: "ready", pagesUrl, repoUrl });
      } else {
        // Запускаем polling — useEffect подхватит waiting_pages
        setDeployState({ phase: "waiting_pages", pagesUrl, repoUrl, attempt: 1, maxAttempts: 24 });
      }
    } catch (err: any) {
      setDeployState({ phase: "error", message: err.message || "Неизвестная ошибка" });
      setTimeout(() => setDeployState({ phase: "idle" }), 8000);
    }
  };

  const handleDeploy = async () => {
    if (!htmlCode) return;

    const title =
      htmlCode.match(/<title>([^<]{1,60})<\/title>/i)?.[1]?.trim() ||
      message.content.slice(0, 30).split("\n")[0] ||
      "Smol Game Prototype";

    if (!isAuthenticated || !isGithubConnected) {
      // Сохраняем игру — она подберётся автоматически после OAuth
      SmolGameAPI.savePendingGame({ htmlCode, title });
      login(); // Редирект на GitHub OAuth
      return;
    }

    await runDeploy(htmlCode, title);
  };

  const handleCopy = async () => {
    try {
      const cleanContent = message.content
        .replace(/<game_prototype>[\s\S]*?(?:<\/game_prototype>|$)/g, "")
        .replace(/<game_spec>[\s\S]*?(?:<\/game_spec>|$)/g, "")
        .replace(/<thought>[\s\S]*?(?:<\/thought>|$)/g, "")
        .trim();
      await navigator.clipboard.writeText(htmlCode || cleanContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const isUser = message.role === "user";
  const isStreaming = message.isStreaming;

  return (
    <div className={`flex gap-4 py-8 px-4 ${isUser ? "bg-transparent" : "bg-[#13141a]/30"}`}>
      <div className="flex-shrink-0">
        <div className={`w-9 h-9 rounded-xl flex items-center justify-center ${isUser ? "bg-[#1c1e26] text-white/50" : "bg-[#a3b8d4]/10 text-[#a3b8d4]"}`}>
          {isUser ? <User size={18} /> : <Bot size={18} />}
        </div>
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-xs font-black uppercase tracking-widest text-white/30">
            {isUser ? "Пользователь" : "Smol Agent"}
          </span>
          <span className="text-[10px] text-white/10">
            {new Date(message.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
          </span>
        </div>
        <div className="prose prose-invert max-w-none">
          {isUser ? (
            <p className="text-white/80 leading-relaxed whitespace-pre-wrap text-sm font-medium">
              {message.content}
            </p>
          ) : (
            <div className="markdown-content text-white/90">
              {message.content ? (
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{
                    ul: ({ node, children, ...props }) => {
                      if (isLast && message.role === "assistant" && onSend) {
                        return <ul className="m-0 p-0 mt-4 mb-2 space-y-2 flex flex-col items-start w-full" {...props}>{children}</ul>;
                      }
                      return <ul className="list-disc pl-4 mt-2 mb-4 space-y-1 text-white/80" {...props}>{children}</ul>;
                    },
                    ol: ({ node, children, ...props }) => {
                      if (isLast && message.role === "assistant" && onSend) {
                        return <ol className="m-0 p-0 mt-4 mb-2 space-y-2 flex flex-col items-start w-full" {...props}>{children}</ol>;
                      }
                      return <ol className="list-decimal pl-4 mt-2 mb-4 space-y-1 text-white/80" {...props}>{children}</ol>;
                    },
                    li: ({ node, children, ...props }) => {
                      if (isLast && message.role === "assistant" && onSend) {
                        const text = extractTextFromNode(node).trim();
                        return (
                          <li className="list-none w-full" {...props}>
                            <button
                              onClick={() => onSend(text)}
                              className="text-left w-full px-4 py-3 bg-[#13141a] hover:bg-[#a3b8d4]/10 border border-white/5 hover:border-[#a3b8d4]/30 rounded-xl text-sm transition-all text-white/80 hover:text-white font-medium group flex items-center justify-between"
                            >
                              <span>{children}</span>
                              <span className="opacity-0 group-hover:opacity-100 shrink-0 text-[#a3b8d4] text-[10px] uppercase font-black tracking-widest ml-4 transition-opacity">
                                Выбрать
                              </span>
                            </button>
                          </li>
                        );
                      }
                      return <li className="mb-1" {...props}>{children}</li>;
                    },
                  }}
                >
                  {(() => {
                    if (message.role !== "assistant") return message.content;
                    const filtered = message.content
                      .replace(/<game_prototype>[\s\S]*?(?:<\/game_prototype>|$)/g, "")
                      .replace(/<game_spec>[\s\S]*?(?:<\/game_spec>|$)/g, "")
                      .replace(/<thought>[\s\S]*?(?:<\/thought>|$)/g, "")
                      .trim();
                    
                    // Если после фильтрации ничего не осталось, но текст в сообщении есть,
                    // значит AI выдал ответ только в тегах. Показываем оригинал.
                    return filtered || message.content;
                  })()}
                </ReactMarkdown>
              ) : isStreaming ? (
                <div className="flex items-center gap-1.5 text-[#a3b8d4]">
                  <div className="w-1.5 h-1.5 rounded-full bg-[#a3b8d4] animate-bounce [animation-delay:0ms]" />
                  <div className="w-1.5 h-1.5 rounded-full bg-[#a3b8d4] animate-bounce [animation-delay:150ms]" />
                  <div className="w-1.5 h-1.5 rounded-full bg-[#a3b8d4] animate-bounce [animation-delay:300ms]" />
                </div>
              ) : null}
            </div>
          )}
        </div>

        {!isUser && message.content && !isStreaming && (
          <div className="flex flex-col gap-4 mt-6">
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="sm"
                className="h-8 px-3 text-[10px] font-bold uppercase tracking-widest text-[#a3b8d4] hover:text-white bg-[#13141a] border border-white/5 rounded-xl transition-all"
                onClick={handleCopy}
              >
                {copied ? <Check size={14} /> : <Copy size={14} />}
                <span className="ml-2">{copied ? "Скопировано" : "Копировать"}</span>
              </Button>
              {htmlCode && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-8 px-3 text-[10px] font-bold uppercase tracking-widest text-green-500 hover:text-green-400 bg-green-500/5 border border-green-500/10 rounded-xl transition-all"
                  onClick={() => setShowPreview(true)}
                >
                  <Play size={14} fill="currentColor" />
                  <span className="ml-2">Быстрый просмотр</span>
                </Button>
              )}
              {onRetry && (
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-8 px-3 text-[10px] font-bold uppercase tracking-widest text-white/30 hover:text-white bg-[#13141a] border border-white/5 rounded-xl transition-all"
                  onClick={onRetry}
                >
                  <RotateCcw size={14} />
                  <span className="ml-2">Переделать</span>
                </Button>
              )}
            </div>

            {message.status && (
              <div className="flex items-center gap-2 text-[10px] text-[#a3b8d4] font-black uppercase tracking-tighter bg-[#a3b8d4]/5 p-3 rounded-xl border border-[#a3b8d4]/10 w-fit">
                <div className="w-1.5 h-1.5 rounded-full bg-[#a3b8d4] animate-pulse" />
                <span>{message.status}</span>
              </div>
            )}

            {message.pipelineResult && (
              <div className="p-4 bg-[#13141a] border border-white/5 rounded-2xl animate-in fade-in zoom-in duration-300">
                <div className="flex items-center justify-between mb-3">
                  <h5 className="text-[10px] font-black uppercase tracking-widest text-white/20">Анализ качества</h5>
                  <span className={`text-xs font-black ${message.pipelineResult.finalScore >= 70 ? "text-green-500" : "text-yellow-500"}`}>
                    {message.pipelineResult.finalScore}/100
                  </span>
                </div>

                <div className="space-y-4">
                  {/* Always show deploy results if they exist */}
                  {(deployState.phase === "ready" || deployState.phase === "waiting_pages" || deployState.phase === "deploying" || deployState.phase === "error") && (
                    <div className="pt-2 border-t border-white/5 mt-2">
                      {deployState.phase === "deploying" && (
                        <div className="flex items-center gap-3 p-3 bg-[#a3b8d4]/5 border border-[#a3b8d4]/15 rounded-xl">
                          <Loader2 size={16} className="animate-spin text-[#a3b8d4] shrink-0" />
                          <span className="text-[11px] text-[#a3b8d4] font-bold">{deployState.status}</span>
                        </div>
                      )}

                      {deployState.phase === "waiting_pages" && (
                        <div className="space-y-3">
                          <div className="flex items-center gap-3 p-3 bg-amber-500/5 border border-amber-500/15 rounded-xl">
                            <Clock size={16} className="text-amber-400 shrink-0 animate-pulse" />
                            <div className="flex-1 min-w-0">
                              <p className="text-[11px] text-amber-400 font-bold">GitHub Pages активируется…</p>
                              <p className="text-[9px] text-white/30 mt-0.5">
                                Попытка {deployState.attempt}/{deployState.maxAttempts}
                              </p>
                            </div>
                          </div>
                        </div>
                      )}

                      {((deployState.phase === "ready" || deployState.phase === "waiting_pages" || deployState.phase === "error") || (message.gameCode)) && (
                        <div className="space-y-3 mt-4">
                          <Button
                            className="w-full h-14 bg-[#22c55e] hover:bg-[#16a34a] text-white font-black uppercase tracking-[0.3em] text-[14px] rounded-2xl gap-3 shadow-[0_12px_24px_-6px_rgba(34,197,94,0.5)] transition-all active:scale-[0.97] hover:shadow-[0_15px_30px_-6px_rgba(34,197,94,0.6)]"
                            onClick={() => {
                              if (onSwitchTab) {
                                onSwitchTab("studio");
                              }
                            }}
                          >
                            <Play size={22} fill="currentColor" className="ml-1" /> ИГРАТЬ
                          </Button>

                          {(deployState.phase === "ready" || deployState.phase === "waiting_pages") && (
                            <div className="grid grid-cols-2 gap-2">
                              <Button
                                variant="outline"
                                className="h-10 bg-white/5 border-white/10 text-white/70 hover:bg-white/10 rounded-xl text-[10px] font-black uppercase tracking-widest gap-2"
                                onClick={() => window.open(deployState.pagesUrl, "_blank")}
                              >
                                <ExternalLink size={14} /> Играть (Web)
                              </Button>
                              <Button
                                variant="outline"
                                className="h-10 bg-white/5 border-white/10 text-white/70 hover:bg-white/10 rounded-xl text-[10px] font-black uppercase tracking-widest gap-2"
                                onClick={() => window.open(deployState.repoUrl, "_blank")}
                              >
                                <Github size={14} /> Репозиторий
                              </Button>
                            </div>
                          )}

                          {deployState.phase === "idle" && message.gameCode && (
                            <Button
                              variant="outline"
                              className="w-full h-10 bg-blue-500/10 border-blue-500/20 text-blue-400 hover:bg-blue-500/20 rounded-xl text-[10px] font-black uppercase tracking-widest gap-2"
                              onClick={() => {
                                // Запускаем ручную публикацию
                                const titleMatch = message.content.match(/(?:название|title|game)[\s:]*([^\n.]{3,40})/i);
                                const gameTitle = titleMatch?.[1]?.trim() || "Smol Game";
                                runDeploy(message.gameCode!, gameTitle);
                              }}
                            >
                              <Github size={14} /> Опубликовать в GitHub
                            </Button>
                          )}

                          <p className="text-[10px] text-white/40 text-center uppercase font-black tracking-widest leading-tight">
                            {deployState.phase === "ready" ? "✨ Игра опубликована в GitHub" : 
                             deployState.phase === "error" ? "⚠️ Ошибка деплоя, но можно играть в Студии" :
                             deployState.phase === "waiting_pages" ? "⌛ Подготовка ссылки для ленты..." :
                             "🛠 Готова к тестированию"}
                          </p>
                        </div>
                      )}

                      {deployState.phase === "error" && (
                        <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-2xl space-y-3">
                          <div className="flex items-center gap-2 text-red-400 font-black uppercase tracking-widest text-[10px]">
                            <X size={14} strokeWidth={3} /> Ошибка публикации
                          </div>
                          <p className="text-[11px] text-white/70 leading-relaxed">{deployState.message}</p>
                          {deployState.message.includes("Сессия Telegram устарела") && (
                            <Button
                              className="w-full h-9 bg-red-500/20 hover:bg-red-500/30 text-red-400 border border-red-500/30 font-black uppercase tracking-widest text-[10px] rounded-xl transition-all"
                              onClick={() => window.location.reload()}
                            >
                              <RotateCcw size={14} className="mr-2" /> Обновить сессию
                            </Button>
                          )}
                        </div>
                      )}
                    </div>
                  )}

                  {!message.pipelineResult.isPublishable && (
                    <div className="space-y-2 pt-2">
                      <p className="text-[10px] text-yellow-500/50 font-bold uppercase tracking-wider">Требуются доработки:</p>
                      {message.pipelineResult.nextSteps.slice(0, 3).map((step: any, i: number) => (
                        <p key={i} className="text-[10px] text-white/40 flex gap-2">
                          <span className="text-[#a3b8d4]">•</span> {step}
                        </p>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        )}

        {showPreview && htmlCode && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/90 backdrop-blur-xl">
            <div className="relative w-full max-w-lg aspect-[9/16] bg-black rounded-[32px] overflow-hidden shadow-2xl border border-white/10 ring-1 ring-white/20">
              <div className="absolute top-6 right-6 z-50">
                <Button
                  variant="ghost"
                  size="sm"
                  className="rounded-full w-10 h-10 p-0 bg-black/50 text-white hover:bg-black border border-white/10"
                  onClick={() => setShowPreview(false)}
                >
                  <X size={20} />
                </Button>
              </div>
              <iframe
                title="Game Preview"
                srcDoc={
                  htmlCode.includes("<!DOCTYPE")
                    ? htmlCode
                    : `<!DOCTYPE html><html><body style="margin:0;overflow:hidden;background:#000;">${htmlCode}</body></html>`
                }
                className="w-full h-full border-none"
                sandbox="allow-scripts allow-pointer-lock allow-same-origin"
              />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
