/**
 * useGameAgent — Агент на базе проверенного llm-api.ts (SSE streaming)
 * Без Vercel AI SDK — используем тот же fetch что работал раньше
 */

import { useState, useRef, useCallback } from "react";
import { generateStream, pool, DEFAULT_MODELS } from "../lib/llm-api";
import type { APIProvider } from "../lib/llm-api";
import { runGamePipeline } from "../lib/core/gameGenerationPipelinePro";
import { SmolGameAPI } from "../lib/smolgame-api";
import type { ChatSettings } from "../types/chat";

export interface AgentMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: number;
  isStreaming?: boolean;
  gameCode?: string;
  pipelineResult?: any;
  deployResult?: any;
  toolCalls?: AgentToolCall[];
}

export interface AgentToolCall {
  name: string;
  status: "running" | "done" | "error";
  input?: any;
  output?: string;
}

function makeId() {
  return Math.random().toString(36).slice(2, 10);
}

const PROVIDER_ORDER: APIProvider[] = [
  "groq", "gemini", "together", "openrouter", "deepseek", "sambanova", "huggingface"
];

const SYSTEM_PROMPT = `Ты — SmolGame Agent, специалист по созданию веб-игр для мобильных.

ЗАДАЧА: Пообщайся с пользователем, собери детали (жанр + механика + стиль) и создай полноценную игру.

ПРАВИЛА:
1. Общайся по-русски, дружелюбно.
2. Задавай по ОДНОМУ вопросу за раз.
3. Когда собрал достаточно деталей — сразу пиши код игры.
4. Код должен быть ПОЛНЫМ (не менее 5000 символов), с requestAnimationFrame, touch-управлением, Start/HUD/GameOver экранами.
5. После кода — опубликуй игру.

КОГДА ГОТОВ СОЗДАТЬ ИГРУ — используй этот формат:
\`\`\`action
{"tool": "createGame", "gameTitle": "Название игры", "gameCode": "<!DOCTYPE html>...ВЕСЬ КОД..."}
\`\`\`

КОГДА ГОТОВ ОПУБЛИКОВАТЬ — используй этот формат:
\`\`\`action
{"tool": "publishGame", "gameTitle": "Название игры", "gameCode": "<!DOCTYPE html>...ВЕСЬ КОД..."}
\`\`\`

Если просто общаешься — отвечай обычным текстом без \`\`\`action блоков.`;

export function useGameAgent(settings: ChatSettings) {
  const [messages, setMessages] = useState<AgentMessage[]>([]);
  const [isRunning, setIsRunning] = useState(false);
  const [step, setStep] = useState("");
  const abortRef = useRef<AbortController | null>(null);
  const chatHistory = useRef<{ role: string; content: string }[]>([]);

  const addMessage = useCallback((msg: Omit<AgentMessage, "id" | "timestamp">) => {
    const full: AgentMessage = { ...msg, id: makeId(), timestamp: Date.now() };
    setMessages(prev => [...prev, full]);
    return full.id;
  }, []);

  const updateMessage = useCallback((id: string, patch: Partial<AgentMessage>) => {
    setMessages(prev => prev.map(m => m.id === id ? { ...m, ...patch } : m));
  }, []);

  const executeAction = useCallback(async (
    toolName: string,
    args: any,
    assistantId: string,
    toolCalls: AgentToolCall[]
  ) => {
    if (toolName === "createGame") {
      const { gameTitle, gameCode } = args;
      toolCalls.push({ name: "createGame", status: "running", input: { gameTitle } });
      updateMessage(assistantId, { content: "🎮 Проверяю качество кода...", toolCalls: [...toolCalls], isStreaming: true });
      try {
        const pipeline = await runGamePipeline("agent-game", gameCode);
        const score = pipeline.finalScore;
        toolCalls[toolCalls.length - 1] = { name: "createGame", status: "done", output: `${score}/100` };
        updateMessage(assistantId, {
          content: `✅ **${gameTitle}** готова! Качество: ${score}/100`,
          gameCode, pipelineResult: pipeline, toolCalls: [...toolCalls], isStreaming: true,
        });
        return { success: true, score, gameCode };
      } catch (e: any) {
        toolCalls[toolCalls.length - 1] = { name: "createGame", status: "error", output: e.message };
        return { success: false };
      }
    }

    if (toolName === "publishGame") {
      const { gameTitle, gameCode } = args;
      toolCalls.push({ name: "publishGame", status: "running" });
      updateMessage(assistantId, { toolCalls: [...toolCalls], isStreaming: true });
      setStep("🚀 Публикую...");
      try {
        const result = await SmolGameAPI.publishGame({
          gameTitle,
          files: [{ path: "index.html", content: gameCode }],
          gameDescription: "Generated by SmolGame Agent",
        });
        if (result.ok) {
          toolCalls[toolCalls.length - 1] = { name: "publishGame", status: "done", output: result.pagesUrl };
          updateMessage(assistantId, {
            deployResult: { pagesUrl: result.pagesUrl, repoUrl: `https://github.com/${result.repo}`, pagesReady: result.pagesReady },
            toolCalls: [...toolCalls],
          });
        } else {
          toolCalls[toolCalls.length - 1] = { name: "publishGame", status: "error", output: result.error };
        }
      } catch (e: any) {
        toolCalls[toolCalls.length - 1] = { name: "publishGame", status: "error", output: e.message };
      }
    }
  }, [updateMessage]);

  const sendMessage = useCallback(async (userText: string) => {
    if (isRunning) return;

    addMessage({ role: "user", content: userText });
    chatHistory.current.push({ role: "user", content: userText });

    const assistantId = addMessage({ role: "assistant", content: "🤔 Думаю...", isStreaming: true });
    setIsRunning(true);
    abortRef.current = new AbortController();

    const activeProviders = PROVIDER_ORDER.filter(p => {
      const key = settings.keys[p as keyof typeof settings.keys] as string | undefined;
      return key && key.trim().length > 0;
    });

    if (activeProviders.length === 0) {
      updateMessage(assistantId, {
        content: "❌ Нет API ключей. Открой настройки (≡) и добавь хотя бы один ключ (Groq, Gemini, OpenRouter и т.д.).",
        isStreaming: false,
      });
      setIsRunning(false);
      return;
    }

    const toolCalls: AgentToolCall[] = [];
    let success = false;
    let lastError = "";

    try {
      for (const providerId of activeProviders) {
        if (abortRef.current?.signal.aborted) break;

        const status = pool.getStatus(providerId);
        if (status.state === "OPEN") {
          const secLeft = Math.round((status.nextRetryAt - Date.now()) / 1000);
          console.log(`[Agent] ${providerId} OPEN — пропускаю (ещё ${secLeft}s)`);
          continue;
        }

        const apiKey = settings.keys[providerId as keyof typeof settings.keys] as string;
        const model = (settings.models?.[providerId as keyof typeof settings.models] as string | undefined)
          || DEFAULT_MODELS[providerId]?.[0] || "gpt-3.5-turbo";

        setStep(`🔄 ${providerId}...`);
        updateMessage(assistantId, { content: `🔄 Подключаю **${providerId}**...`, isStreaming: true });

        try {
          let fullText = "";

          const msgs = [
            { role: "system" as const, content: SYSTEM_PROMPT },
            ...chatHistory.current.slice(-12).map(m => ({
              role: m.role as "user" | "assistant" | "system",
              content: m.content
            })),
          ];

          for await (const chunk of generateStream(msgs, { provider: providerId, apiKey, model }, abortRef.current.signal)) {
            if (abortRef.current?.signal.aborted) break;
            fullText += chunk;
            const visibleText = fullText.split("```action")[0].trim();
            updateMessage(assistantId, { content: visibleText || "💬 ...", isStreaming: true });
          }

          // Парсим action-блок
          const actionMatch = fullText.match(/```action\s*\n([\s\S]*?)\n?```/);
          if (actionMatch) {
            try {
              const action = JSON.parse(actionMatch[1].trim());
              if (action.tool && action.gameTitle && action.gameCode) {
                await executeAction(action.tool, action, assistantId, toolCalls);
              }
            } catch (e) {
              console.warn("[Agent] Не удалось распарсить action:", e);
            }
          }

          const visibleText = fullText.split("```action")[0].trim();
          updateMessage(assistantId, {
            content: visibleText || "Готово!",
            isStreaming: false,
            toolCalls: toolCalls.length > 0 ? toolCalls : undefined,
          });

          chatHistory.current.push({ role: "assistant", content: fullText });
          pool.reportSuccess(providerId);
          success = true;
          break;

        } catch (e: any) {
          lastError = e.message || "Неизвестная ошибка";
          const isRateLimit = lastError.includes("429") || lastError.toLowerCase().includes("rate limit");
          pool.reportFailure(providerId, isRateLimit, lastError);
          console.warn(`[Agent] ${providerId} failed:`, lastError.slice(0, 120));
        }
      }

      if (!success) {
        const summary = pool.getSummary(activeProviders);
        updateMessage(assistantId, {
          content: `❌ Все провайдеры недоступны.\n\n**Ошибка:** \`${lastError.slice(0, 150)}\`\n\n${summary}\n\nПроверь ключи в настройках (≡).`,
          isStreaming: false,
        });
      }
    } finally {
      setIsRunning(false);
      setStep("");
    }
  }, [isRunning, settings, addMessage, updateMessage, executeAction]);

  const stop = useCallback(() => {
    abortRef.current?.abort();
    setIsRunning(false);
    setStep("");
  }, []);

  const reset = useCallback(() => {
    setMessages([]);
    chatHistory.current = [];
  }, []);

  return { messages, isRunning, step, sendMessage, stop, reset };
}
