import express from 'express';
import cors from 'cors';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';
import { 
  Config, 
  GeminiClient, 
  createContentGenerator, 
  createContentGeneratorConfig,
  AuthType
} from '../packages/core/src/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const app = express();
app.use(cors());
app.use(express.json());

app.post('/api/generate', async (req, res) => {
  const { prompt, apiKey, model, provider } = req.body;

  if (!prompt) return res.status(400).json({ error: 'Prompt is required' });

  // 1. Create a temp directory for the game
  const gameId = `game_${Date.now()}`;
  const workspacePath = join(root, 'temp_workspaces', gameId);
  fs.mkdirSync(workspacePath, { recursive: true });

  console.log(`[OpenGame API] Starting generation for ${gameId} in ${workspacePath}`);

  try {
    // 2. Initialize OpenGame Config
    const config = new Config();
    config.setSessionId(gameId);
    
    let authType = AuthType.USE_OPENAI;
    if (provider === 'gemini') authType = AuthType.USE_GEMINI;
    if (provider === 'anthropic') authType = AuthType.USE_ANTHROPIC;
    
    const generatorConfig = createContentGeneratorConfig(config, authType, {
      model: model || 'gpt-4o',
      apiKey: apiKey,
      baseUrl: provider === 'openrouter' ? 'https://openrouter.ai/api/v1' : undefined
    });

    // Set env keys for OpenGame core to pick up
    if (authType === AuthType.USE_OPENAI) process.env['OPENAI_API_KEY'] = apiKey;
    if (authType === AuthType.USE_GEMINI) process.env['GEMINI_API_KEY'] = apiKey;
    if (provider === 'openrouter') process.env['OPENAI_BASE_URL'] = 'https://openrouter.ai/api/v1';

    const generator = await createContentGenerator(generatorConfig, config);
    config.setContentGenerator(generator);

    const client = new GeminiClient(config);
    await client.initialize();
    
    // CRITICAL: Enable tools for the engine to be "smart"
    await client.setTools();

    // 3. Send the prompt to OpenGame
    const fullPrompt = `TASK: Create a professional, single-file web game.
    REQUIREMENTS:
    ${prompt}
    
    CONSTRAINTS:
    - Language: Russian for UI, English for code.
    - Style: Premium, modern, animated.
    - File: MUST be index.html only.
    - Quality: Adhere to all 35 SmolGame quality standards mentioned in the prompt.
    
    Use your planning tools (TODO_WRITE) to break this down and verify your work.`;

    // This is a simplified version of the CLI loop
    const stream = client.sendMessageStream([{ text: fullPrompt }], new AbortController().signal, gameId);
    
    for await (const event of stream) {
      // Here we could stream progress back to the client
      if (event.type === 'error') throw new Error(event.value);
    }

    // 4. Read the generated file
    const indexPath = join(workspacePath, 'index.html');
    if (fs.existsSync(indexPath)) {
      const code = fs.readFileSync(indexPath, 'utf8');
      res.json({ success: true, code, gameId });
    } else {
      // Fallback: try to find any html file
      const files = fs.readdirSync(workspacePath);
      const htmlFile = files.find(f => f.endsWith('.html'));
      if (htmlFile) {
        const code = fs.readFileSync(join(workspacePath, htmlFile), 'utf8');
        res.json({ success: true, code, gameId });
      } else {
        throw new Error('No HTML file was generated by OpenGame engine.');
      }
    }
  } catch (error: any) {
    console.error(`[OpenGame API] Error:`, error);
    res.status(500).json({ error: error.message });
  } finally {
    // Cleanup workspace (optional)
    // fs.rmSync(workspacePath, { recursive: true, force: true });
  }
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`🚀 OpenGame API Server running on http://localhost:${PORT}`);
});
